#!/bin/bash
#
# copybacktrunk.sh - deploy a FOG git checkout's web tree to the live webroot.
#
# Direction: GIT -> WEB. Use this after editing in the repository to test the
# change on a running server. The reverse direction is CopyToSVN.
#
# Usage:
#   copybacktrunk.sh [repo-path] [config-path] [version-suffix]
#
# All three are optional and can also be supplied as environment variables:
#
#   path        the git checkout                 (default: $HOME/fogproject)
#   configpath  config.class.php to install      (default: /opt/fog/config.class.php)
#   ver         webroot version suffix, or empty (default: empty)
#   webroot     destination document root        (default: /var/www/fog)
#   webuser     owner of the deployed tree       (default: apache, or nginx if present)
#   webgroup    group of the deployed tree       (default: same as webuser)
#
# The version suffix exists for servers that keep several trees side by side
# (/var/www/html/fog-1.5, fog-1.6, ...) and symlink the live one. Leave it unset
# for an ordinary single-version install and nothing is symlinked.
#
set -u

path=${1:-${path:-}}
configpath=${2:-${configpath:-}}
ver=${3:-${ver:-}}

[[ -z "$path" || ( ! -e "$path" && ! -e "$HOME/$path" ) ]] && path="$HOME/fogproject"
[[ -e "$HOME/$path" && ! -e "$path" ]] && path="$HOME/$path"

# Pick the web user the way the installer does: whichever service is actually
# installed. Overridable because a custom build may use neither name.
if [[ -z ${webuser:-} ]]; then
    if id -u nginx >/dev/null 2>&1; then
        webuser=nginx
    else
        webuser=apache
    fi
fi
webgroup=${webgroup:-$webuser}

# With a version suffix the tree lives beside its siblings and /var/www/html/fog
# points at whichever is current; without one it is just the webroot.
if [[ -n $ver ]]; then
    webroot=${webroot:-/var/www/html/fog-${ver}}
    weblink=${weblink:-/var/www/html/fog}
else
    webroot=${webroot:-/var/www/fog}
    weblink=""
fi

# config.class.php is generated at install time and is NOT in git, so it has to
# be kept outside the checkout and copied back in after every deploy.
if [[ -z $configpath ]]; then
    if [[ -n $ver && -e /opt/fog/config-${ver}.class.php ]]; then
        configpath="/opt/fog/config-${ver}.class.php"
    else
        configpath="/opt/fog/config.class.php"
    fi
fi
[[ ! -e $configpath ]] && {
    echo "No configuration file available. Please make sure this file exists: ${configpath}"
    exit 1
}

# Installer-owned paths under the webroot. These are NOT in packages/web, so
# --delete removes them on every run; and the ones that DO exist in both get the
# repo's copy written over the installer's. Either way a code deploy quietly
# undoes installer state, so exclude them.
#
# Patterns are relative to the rsync SOURCE ROOT and quoted so the shell does
# not glob them first. An --exclude given as an absolute path
# ($path/packages/web/fog_*.log) is one rsync can never match -- and unquoted,
# a glob that did expand would have turned the extra matches into additional
# rsync SOURCE arguments.
excludes=(
    # Runtime logs, 0200 and owned by the web user.
    --exclude='fog_*.log'
    # MOK enrolment kit, published by the installer's _publishSecureBootKit.
    # Deleting it is what makes the Secure Boot page fall back to "not
    # configured on this server" after a deploy.
    --exclude='service/secureboot/'
    # Server certificate issued at install time.
    --exclude='management/other/ssl/'
    # Generated at deploy time and re-copied below.
    --exclude='lib/fog/config.class.php'
    # Generated by the installer (GH-850); defines FOG_BASE_DIR, which
    # commons/init.php loads before the autoloader. Deleting it is a fatal
    # undefined-constant on every page, and it is what FOGPage's
    # secureBootStagingDir()/fog-sign-kernel lookup resolves against.
    --exclude='commons/fogpaths.php'
    # Installer-written sample config.
    --exclude='kea-dhcp4.conf.fog-sample'
    # Compiled translations: gitignored, so they exist only in the deployed
    # tree. Deleting them silently drops every non-English UI string.
    --exclude='*.mo'
    # Downloaded FOS binaries, not source. The DEPLOYED copies are signed for
    # Secure Boot and the repo copies are not, so syncing these reverts the
    # kernels to unsigned -- Secure Boot clients then stop booting with nothing
    # on the server to explain why. Re-run installfog.sh to update kernels.
    --exclude='service/ipxe/bzImage*'
    --exclude='service/ipxe/init*.xz'
    --exclude='service/ipxe/arm_Image*'
    --exclude='service/ipxe/arm_init.cpio.gz'
    # _resignKernels' pre-signature snapshots of the above.
    --exclude='*.unsigned'
)

sudo rsync -a --no-links -heP --delete "${excludes[@]}" \
    "$path/packages/web/" "$webroot"

# Not shipped to a live server; it is the installer's holding page.
sudo rm -rf "${webroot}/maintenance"

sudo cp "$configpath" "${webroot}/lib/fog/config.class.php"
sudo chown -R "${webuser}":"${webgroup}" "$webroot"
sudo chown -R fogproject:"${webgroup}" "${webroot}/service/ipxe"

# Logs are write-only for the web user; the rsync above restores repo modes on
# anything it did copy, so reassert it here.
sudo chmod 0200 "${webroot}"/fog_*.log 2>/dev/null

# Multi-version layout only: point /var/www/html/fog at this tree, and give the
# tree a self-referential "fog" link so a URL of /fog/fog/... still resolves.
if [[ -n $weblink ]]; then
    sudo rm -f "$weblink"
    sudo ln -sf "$webroot" "$weblink"
    sudo rm -f "${webroot}/fog"
    sudo ln -sf "$webroot" "${webroot}/fog"
fi

# Reload so opcache does not keep serving the previous copy of changed files.
for svc in nginx httpd apache2 php-fpm; do
    systemctl is-active --quiet "$svc" 2>/dev/null && sudo systemctl restart "$svc"
done

exit 0
