Host debian10
    User root
    HostName debian10.fogtesting.cloud
    Port 22
Host debian11
    User root
    HostName debian11.fogtesting.cloud
    Port 22
Host centos7
    User root
    HostName centos7.fogtesting.cloud
    Port 22
Host centos8
    User root
    HostName centos8.fogtesting.cloud
    Port 22
Host fedora35
    User root
    HostName fedora35.fogtesting.cloud
    Port 22
Host almalinux8
    User root
    HostName almalinux8.fogtesting.cloud
    Port 22
Host rockylinux8
    User root
    HostName rockylinux8.fogtesting.cloud
    Port 22
Host rhel7
    User root
    HostName rhel7.fogtesting.cloud
    Port 22
Host rhel8
    User root
    HostName rhel8.fogtesting.cloud
    Port 22
Host ubuntu16_04
    User root
    HostName ubuntu16_04.fogtesting.cloud
    Port 22
Host ubuntu18_04
    User root
    HostName ubuntu18_04.fogtesting.cloud
    Port 22
Host ubuntu20_04
    User root
    HostName ubuntu20_04.fogtesting.cloud
    Port 22
