Host debian9
    User root
    HostName debian9.fogtesting.cloud
    Port 22
Host centos7
    User root
    HostName centos7.fogtesting.cloud
    Port 22
Host rhel7
    User root
    HostName rhel7.fogtesting.cloud
    Port 22
Host fedora30
    User root
    HostName fedora30.fogtesting.cloud
    Port 22
Host arch
    User root
    HostName arch.fogtesting.cloud
    Port 22
Host ubuntu18_04
    User root
    HostName ubuntu18_04.fogtesting.cloud
    Port 22
